#ifndef DOCUMENT_H
#define DOCUMENT_H

const char *docTerms =
    "<html><head/><body><p>\n"
    "BY ACCESSING, USING, INSTALLING OR DOWNLOADING KelVPN App\n"
    "YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD THESE\n"
    "TERMS (AGREEMENT) AND AGREE TO BE BOUND BY THEM AND TO\n"
    "FULLY COMPLY WITH THEM. YOU FURTHER AGREE TO COMPLY WITH\n"
    "ALL APPLICABLE LAWS AND REGULATIONS REGARDING YOUR USE OF\n"
    "KelVPN AND YOU ACKNOWLEDGE THAT THESE TERMS CONSTITUTE A\n"
    "BINDING AND ENFORCEABLE LEGAL ELECTRONIC CONTRACT BETWEEN\n"
    "YOU AND US. IF YOU DO NOT AGREE, DO NOT ACCESS, INSTALL,\n"
    "DOWNLOAD OR USE KelVPN AS DEFINED BELOW.</p><p>\n"
    "<b>1. Service provider</b></p><p>\n"
    "The service Kelvin Virtual Private Network (here and after called KelVPN) is\n"
    "hereby offered by Demlabs Inc, 7901 4th Street North STE 300 St. Petersburg, FL.\n"
    "US 33702 (hereinafter called Demlabs Ltd). Demlabs Ltd is authorized to provide\n"
    "Users with KelVPN on the basis of the agreement with the owner of KelVPN\n"
    "software. The owner of KelVPN is Demlabs Limited. Certificate of Incorporation\n"
    "issued on 10 March 2020 # 2922266 9/F, Unit D, Neich Tower, 128 Gloucester Road,\n"
    "Wanchai, Hong Kong, 999077.</p><p>\n"
    "<b>2. Agreement</b></p><p>\n"
    "This agreement is concluded between Demlabs Ltd and you, as User of KelVPN.</p><p>\n"
    "Demlabs Ltd hereby grants you a personal, non-exclusive, not transferable, limited\n"
    "and revocable license to use KelVPN App solely in accordance with the terms of\n"
    "this Agreement. Demlabs Ltd reserves all right, title and interest not expressly granted\n"
    "herein under this license to the fullest extent possible under applicable laws. You may\n"
    "not sublicense, assign, or transfer the license granted to you herein, and any attempt to\n"
    "sublicense, assign, or transfer any part of your rights under this Agreement is void.</p><p>\n"
    "You are allowed to use KelVPN only if you are legally capacitated and authorized\n"
    "to conclude an agreement with Demlabs Ltd and such conclusion is not forbidden to\n"
    "you according to the applicable laws.</p><p>\n"
    "You hereby represent and warrant that you will use KelVPN solely for privacy and\n"
    "security needs and in full compliance with all applicable local, state, national, and\n"
    "international laws, rules and regulations. You shall not agree to, nor shall you\n"
    "authorize or encourage any third party to: (i) prevent others from using KelVPN;\n"
    "(ii) use KelVPN for any fraudulent or inappropriate or illegal purpose (i.e., cyber\n"
    "activity); or (iii) act in any way that violates this Agreement.</p><p>\n"
    "The fee may be charged for KelVPN license. The sum of fee and other specific\n"
    "conditions depend on fee plan that you choose.</p><p>\n"
    "As for all operations with your payment data, they are processed by Demlabs Inc,\n"
    "7901 4th Street North STE 300 St. Petersburg, FL. US 33702. For all operations,\n"
    "which imply the storage of payment data, Demlabs Inc cooperates with third-party\n"
    "providers, who undertake the separate storage of data.</p><p>\n"
    "<b>3. Your data traffic, your data and data security</b></p><p>\n"
    "Demlabs Ltd should provide you with the possibility to perform internet traffic using\n"
    "a computer or other devices in various regions and to keep your IP address hidden.\n"
    "Your data traffic is thus encrypted and cannot be spied out. The goal of KelVPN is\n"
    "to protect your privacy but not your devices. KelVPN is not meant as an antivirus\n"
    "or antimalware tool.</p><p>\n"
    "<b>4. Modifications and Updates</b></p><p>\n"
    "From time to time, Demlabs Ltd at its absolute discretion, can modify KelVPN\n"
    "Apps, for example by adding or removing certain functions of VPN or by updating the\n"
    "software.</p><p>\n"
    "Demlabs Ltd may, at its sole discretion, provide limited technical support, upgrades\n"
    "and updates for KelVPN Apps. In order to enhance and further develop\n"
    "KelVPN we may automatically download and install updates and upgrades from\n"
    "time to time. You hereby agree to receive such updates and upgrades as part of your\n"
    "use of KelVPN. Additionally, we shall have no obligation to provide support or\n"
    "maintenance for KelVPN under this Agreement.</p><p>\n"
    "<b>5. External service providers</b></p><p>\n"
    "WE DISCLAIM ALL REPRESENTATIONS AND WARRANTIES REGARDING\n"
    "CONTENT, GOODS, SOFTWARE OR SERVICES YOU OBTAIN FROM THIRD\n"
    "PARTY PROVIDERS.</p><p>\n"
    "<b>6. Your responsibility</b></p><p>\n"
    "As KelVPN may be accessed from all around the world, you undertake to ensure\n"
    "that your use of KelVPN will comply with all applicable local laws and\n"
    "regulations. Demlabs Ltd takes no responsibility in enforcing such regulations or\n"
    "restrictions and it is your sole responsibility to ensure compliance with the laws\n"
    "applied to you, which may be different in each jurisdiction from which you use\n"
    "KelVPN. You undertake to comply with all applicable laws, rules and regulations\n"
    "and warrant that you will not and will not permit any third party to use the service in\n"
    "any manner that may breach applicable law or infringe third party rights. Without\n"
    "limiting the generality of the above, you undertake and warrant that you will not and\n"
    "will not allow a third party to (A) reverse engineer, disassemble, decompile, translate,\n"
    "reconstruct, transform or extract any portion of KelVPN (including without\n"
    "limitation any related malware signatures and malware detection routines), or (B)\n"
    "change, modify or otherwise alter KelVPN (including without limitation any\n"
    "related malware signatures and malware detection routines); (C) publish, resell,\n"
    "distribute, broadcast, transmit, communicate, transfer, pledge, rent, share or sublicense\n"
    "KelVPN; (D) use KelVPN to provide or build a product or service that\n"
    "competes with KelVPN; (E) contain any unlawful, harmful, threatening, abusive,\n"
    "defamatory or otherwise objectionable material of any kind; or otherwise in any way\n"
    "damage, disable or impair the operation of KelVPN; (F) gain or attempt to gain\n"
    "unauthorized access to KelVPN or to networks connected to it, or to content stored\n"
    "or delivered through it, by any means, including by hacking, spoofing or seeking tocircumvent or defeat any firewalls or other technological or other protections or\n"
    "security measures.</p><p>\n"
    "The present use agreement, the applicable laws and other provisions are binding for\n"
    "you and you are the only one responsible for the observance thereof.</p><p>\n"
    "<b>7. Disclaimer</b></p><p>\n"
    "Demlabs Ltd provides no warranty the service or the software. Demlabs Ltd is not\n"
    "liable for damages which may occur following the exposure of the identity or the IP\n"
    "address of the user or the breakdown of individual user device. Moreover, Demlabs\n"
    "Ltd provides no warranty for the availability of certain VPN nodes within KelVPN\n"
    "network and for the performance thereof.</p><p>\n"
    "EXCEPT AS OTHERWISE SPECIFICALLY PROVIDED HEREIN, KelVPN IS\n"
    "PROVIDED “AS IS” AND Demlabs Ltd MAKES NO EXPRESS OR IMPLIED\n"
    "WARRANTIES OR CONDITIONS AND, TO THE MAXIMUM EXTENT\n"
    "PERMITTED BY LAW, DISCLAIM ANY AND ALL CONDITIONS AND\n"
    "WARRANTIES IMPLIED BY STATUTE, COMMON LAW, JURISPRUDENCE OR\n"
    "OTHER THEORIES OF LAW, INCLUDING BUT NOT LIMITED TO IMPLIED\n"
    "WARRANTIES OR CONDITIONS OF NON INFRINGEMENT OF THIRD PARTY\n"
    "RIGHTS, MERCHANTABILITY, SUITABLE QUALITY OR FITNESS FOR ANY\n"
    "PARTICULAR PURPOSE. Demlabs Ltd DOES NOT WARRANT THAT THE\n"
    "OPERATION OF KelVPN WILL BE UNINTERRUPTED OR ERROR FREE,\n"
    "THAT IT WILL WORK PROPERLY ON ANY GIVEN DEVICE OR WITH ANY\n"
    "PARTICULAR CONFIGURATION OF HARDWARE AND/OR SOFTWARE, OR\n"
    "THAT IT WILL PROVIDE COMPLETE PROTECTION FOR THE INTEGRITY OF\n"
    "SELECTED DATA, INFORMATION OR CONTENT STORED OR\n"
    "TRANSMITTED VIA THE INTERNET.</p><p>\n"
    "<b>8. Indemnification</b></p><p>\n"
    "The user is solely responsible for his or her actions when using KelVPN.</p><p>\n"
    "<b>9. Termination</b></p><p>\n"
    "Prepaid payment plans do not require any termination and end automatically upon\n"
    "expiry of their validity term.</p><p>\n"
    "Demlabs Ltd can terminate at any time the Agreement by providing with relevant\n"
    "notice at is discretion.</p><p>\n"
    "Demlabs Ltd can also terminate extraordinary at any time the Agreement in case of an\n"
    "atypical use. Upon termination of this Agreement, all licenses granted herein will be\n"
    "terminated and you will no longer have access to KelVPN.</p><p>\n"
    "<b>10. Amendments</b></p><p>\n"
    "Demlabs Ltd reviews these Terms from time to time and the updated version is always\n"
    "published on our website. Then, you can accept the amendments to be able to further\n"
    "use KelVPN.</p><p>\n"
    "<b>Service description of KelVPN</b></p><p>\n"
    "Demlabs Ltd provides the following services:</p><p>\n"
    "<b>1.1 Virtual Private Network</b></p><p>\n"
    "You can connect to Kelvin Virtual Private Network (KelVPN) by using an end\n"
    "device via the Internet. For this purpose, Demlabs Ltd makes available the\n"
    "infrastructure, comprising blockchain nodes spread all over the world. We can’t\n"
    "predict in advance whether there will be a node in the location where you need to use\n"
    "VPN. However, you can always choose the node nearest to your current location.</p><p>\n"
    "<b>1.2 Nodes as servers</b></p><p>\n"
    "KelVPN has the decentralized infrastructure based on blockchain nodes. These\n"
    "nodes can be located anywhere. Nodes are devices (PC, smartphones, space in fog\n"
    "services, etc.) provided by anyone who wants to join CellFrame blockchain platform\n"
    "developed by Demlabs Ltd.</p><p>\n"
    "<b>Protocols</b></p><p>\n"
    "KelVPN applies quantum resistant protocols from the short list of NIST PQC\n"
    "contest. New protocols with post-quantum encryption will be implementing in\n"
    "KelVPN on regular basis. Also, KelVPN applies garlic packaging with onion\n"
    "routing and other methods of traffic obfuscation to make user’s traffic more protected.</p><p>\n"
    "<b>2. Access</b></p><p>\n"
    "Your access and use of KelVPN is made via the Internet.</p><p>\n"
    "You must install KelVPN Apps and/or KelVPN Client Software.</p><p>\n"
    "<b>3. Online Support</b></p><p>\n"
    "Demlabs Ltd may provide you with Online-Help on-demand over the Internet in\n"
    "English.</p><p>\n"
    "</p></body></html>";

const char *docPrivacy =
    "<html><head/><body><p>Last updated  12 November, 2021</p><p>\n"
    "The service Kelvin Virtual Private Network (here and after called KelVPN) is\n"
    "hereby offered by Demlabs Inc, 7901 4th Street North STE 300 St. Petersburg, FL.\n"
    "US 33702 (hereinafter called Demlabs Ltd). Demlabs Ltd is authorized to provide\n"
    "Users with KelVPN on the basis of the agreement with the owner of KelVPN\n"
    "software. The owner of KelVPN is Demlabs Limited. Certificate of Incorporation\n"
    "issued on 10 March 2020 # 2922266 9/F, Unit D, Neich Tower, 128 Gloucester Road,\n"
    "Wanchai, Hong Kong, 999077.</p><p>\n"
    "This document (hereinafter - the “Privacy Policy”) explains the privacy rules\n"
    "applicable to KelVPN service.</p><p>\n"
    "Demlabs Ltd doesn’t store and process your email, login, and password in order to\n"
    "provide you access to KelVPN services. You need only a 16-symbols key to get\n"
    "access to KelVPN.</p><p>\n"
    "Due to the specificity of KelVPN blockchain architecture, we don’t have the ability to\n"
    "collect and store user data, such as name, age, preferences, precise location, IP, and\n"
    "any other personal information by which a user can be recognized.</p><p>\n"
    "We also collect some depersonalized statistical data such as the number of KelVPN\n"
    "apps downloads and an operational system to which a user installs our apps. The\n"
    "purpose is to understand our markets and provide our services more efficiently. We\n"
    "don’t transfer or sell this information to third parties or to anyone else. Due to all\n"
    "these, you can be sure that we accurately store and process the information defined in\n"
    "this Policy and it will never be sold/transferred to third parties or anyone else.</p><p>\n"
    "By downloading KelVPN Apps to your device (a computer, a smartphone, etc.) you\n"
    "make us sure that you give us your consent to collect and process data mentioned in\n"
    "this Policy for purposes mentioned above. You are informed that you can revoke this\n"
    "consent at any time by emailing us.</p><p>\n"
    "As for all operations with your payment data, they are processed by Demlabs Ltd,\n"
    "7901 4th Street North STE 300 St. Petersburg, FL. US 33702. For all operations,\n"
    "which imply the storage of payment data, Demlabs Ltd cooperates with third-party\n"
    "providers, who undertake the separate storage of data.</p><p>\n"
    "Please contact us by email at info@demlabsinc.com if you have any questions on our\n"
    "Privacy Policy or you want to enforce any of your rights related to your privacy.</p><p>\n"
    "</p></body></html>\n";

const char *docPrivacyRu =
    "<html><head/><body><p>Последнее обновление: 8 сентября 2020</p><p>Услуга Виртуальная частная сеть Kel (далее именуемая KelVPN) предоставляется Demlabs Limited, свидетельство о регистрации, выданное 10 марта 2020 года #2922266, адрес зарегистрированного офиса компании: 6/F, OTB, 160 Gloucester Road, Wanchai, Hong Kong (далее именуемая Demlabs Ltd).</p><p>Этот документ (далее - «Политика конфиденциальности») объясняет правила конфиденциальности, применимые к сервису KelVPN. </p><p>Demlabs Ltd не хранит и не обрабатывает вашу электронную почту, логин и пароль, чтобы предоставить вам доступ к сервисам KelVPN. Для доступа к KelVPN вам понадобится всего лишь 16-символьный ключ. </p><p>Из-за специфики архитектуры блокчейна KelVPN у нас нет возможности собирать и хранить данные пользователя, такие как имя, возраст, предпочтения, точное местоположение, IP-адрес и любую другую личную информацию, по которой можно распознать пользователя. </p><p>Мы собираем некоторые обезличенные статистические данные, такие как количество загрузок приложений KelVPN и количество загрузок для той или иной операционной системы. Цель состоит в том, чтобы понять наши рынки и более эффективно предоставлять наши услуги. Мы не передаем и не продаем эту информацию третьим лицам или кому-либо еще. Благодаря всему этому вы можете быть уверены, что мы точно храним и обрабатываем информацию, определенную в настоящей Политике, и никогда не будет продана / передана третьим лицам или кому-либо еще. </p><p>Для всех операций, которые подразумевают хранение платежных данных, Demlabs Ltd сотрудничает со сторонними поставщиками, которые берут на себя отдельное хранение данных.</p><p>Загружая приложения KelVPN на свое устройство (компьютер, смартфон и т. д.), Вы гарантируете, что даете нам свое согласие на сбор и обработку данных, упомянутых в настоящей Политике, для целей, упомянутых выше. </p><p>Пожалуйста, свяжитесь с нами по электронной почте info@kelvpn.com  если у вас есть какие-либо вопросы по нашей Политике конфиденциальности.</p></body></html>\n";

#endif // DOCUMENT_H
